### ISSUE TITLE
Anyone else unable to get pgbouncer-rr-path to merge?

### ISSUE THREAD

**Issue by TroyMcl** [awslabs/pgbouncer-rr-patch#45] opened 2020-02-07 23:56 UTC
I have started up 3 new AWS instances and followed the instillation directions.  Every time I get this error.  I saw a similar error was closed and fixed a few days ago but it seems like the issue is still there. Here is the error I get every time

[root@ip-172-31-18-91 /]# git clone https://github.com/pgbouncer/pgbouncer.git
Cloning into 'pgbouncer'...
remote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (21/21), done.
remote: Total 6473 (delta 8), reused 14 (delta 5), pack-reused 6447
Receiving objects: 100% (6473/6473), 2.68 MiB | 14.70 MiB/s, done.
Resolving deltas: 100% (4139/4139), done.
[root@ip-172-31-18-91 /]# git clone https://github.com/awslabs/pgbouncer-rr-patch.git
Cloning into 'pgbouncer-rr-patch'...
remote: Enumerating objects: 190, done.
remote: Total 190 (delta 0), reused 0 (delta 0), pack-reused 190
Receiving objects: 100% (190/190), 137.54 KiB | 8.09 MiB/s, done.
Resolving deltas: 100% (99/99), done.
[root@ip-172-31-18-91 /]# cd pgbouncer-rr-patch
[root@ip-172-31-18-91 pgbouncer-rr-patch]# ./install-pgbouncer-rr-patch.sh ../pgbouncer
Merging pgbouncer-rr changes to: ../pgbouncer/Makefile
patching file Makefile
Hunk #1 succeeded at 23 with fuzz 2 (offset 1 line).
Hunk #2 FAILED at 45.
Hunk #3 FAILED at 81.
2 out of 3 hunks FAILED -- saving rejects to file Makefile.rej
Merging pgbouncer-rr changes to: ../pgbouncer/src/client.c
patching file src/client.c
Hunk #1 succeeded at 479 (offset 33 lines).
Hunk #2 succeeded at 860 (offset 182 lines).
Merging pgbouncer-rr changes to: ../pgbouncer/src/main.c
patching file src/main.c
Hunk #1 succeeded at 150 (offset 11 lines).
Hunk #2 succeeded at 290 with fuzz 2 (offset 20 lines).
Merging pgbouncer-rr changes to: ../pgbouncer/include/bouncer.h
patching file include/bouncer.h
Hunk #1 FAILED at 88.
Hunk #2 succeeded at 504 (offset 47 lines).
1 out of 2 hunks FAILED -- saving rejects to file include/bouncer.h.rej
copying pgbouncer-rr files: README.md LICENSE.txt NOTICE.txt pgbouncer-example.ini users.txt rewrite_query.py routing_rules.py images/diagram1.jpg images/diagram2-routing.jpg images/diagram3-rewrite.jpg src/pycall.c src/rewrite_query.c src/route_connection.c include/pycall.h include/rewrite_query.h include/route_connection.h 
Failures encountered during merge of pgbouncer-rr with pgbouncer.
See error messages above.
Possible causes: 
   pgbouncer-rr-patch already installed in target directory?
   incompatible version of pgbouncer with changed source files that can't be patched?
      - last updated and tested with pgbouncer v1.9.0
Status: pgbouncer-rr-patch merge FAILED

**Comment by rstrahan** [comment] 2020-02-09 17:53
Duplicate of #42
For now, workaround is to checkout pgbouncer v1.10.0 and use that version for pgbouncer-rr.

Replace the documented pgbouncer clone command with:
git clone https://github.com/pgbouncer/pgbouncer.git --branch "pgbouncer_1_10_0"
before installing the patch.

Sorry I don't have time to fix right now - looks like the patch merge is in bouncer.h. If you, or any other comunity member, can figure out how to fix please feel free to send a PR..

**Comment by rstrahan** [comment] 2020-04-26 20:36
Compatability with pgbouncer 1.12 committed in https://github.com/awslabs/pgbouncer-rr-patch/commit/5d5cd0f57601717118dd8ec6c7f34c9537854a6e

**Closed by rstrahan** 2020-04-26 20:36 UTC
