### ISSUE TITLE
Failures encountered during merge of pgbouncer-rr with pgbouncer

### ISSUE THREAD

**Issue by psaripalli-chwy** [awslabs/pgbouncer-rr-patch#43] opened 2019-09-10 13:46 UTC
Got below error when trying to merge:

Followed the same exact same steps listed: https://github.com/awslabs/pgbouncer-rr-patch#getting-started
AWS AMI: amzn2-ami-hvm-2.0.20190618-x86_64-gp2

pgbouncer-rr-patch]# ./install-pgbouncer-rr-patch.sh ../pgbouncer
Merging pgbouncer-rr changes to: ../pgbouncer/Makefile
patching file Makefile
Hunk #1 succeeded at 23 with fuzz 2 (offset 1 line).
Hunk #2 FAILED at 45.
Hunk #3 succeeded at 95 (offset 14 lines).
1 out of 3 hunks FAILED -- saving rejects to file Makefile.rej
Merging pgbouncer-rr changes to: ../pgbouncer/src/client.c
patching file src/client.c
Hunk #1 succeeded at 477 (offset 31 lines).
Hunk #2 succeeded at 857 (offset 179 lines).
Merging pgbouncer-rr changes to: ../pgbouncer/src/main.c
patching file src/main.c
Hunk #1 succeeded at 142 (offset 3 lines).
Hunk #2 succeeded at 280 with fuzz 1 (offset 10 lines).
Merging pgbouncer-rr changes to: ../pgbouncer/include/bouncer.h
patching file include/bouncer.h
Hunk #1 FAILED at 88.
Hunk #2 succeeded at 496 (offset 39 lines).
1 out of 2 hunks FAILED -- saving rejects to file include/bouncer.h.rej
copying pgbouncer-rr files: README.md LICENSE.txt NOTICE.txt pgbouncer-example.ini users.txt rewrite_query.py routing_rules.py images/diagram1.jpg images/diagram2-routing.jpg images/diagram3-rewrite.jpg src/pycall.c src/rewrite_query.c src/route_connection.c include/pycall.h include/rewrite_query.h include/route_connection.h
Failures encountered during merge of pgbouncer-rr with pgbouncer.
See error messages above.
Possible causes:
   pgbouncer-rr-patch already installed in target directory?
   incompatible version of pgbouncer with changed source files that can't be patched?
      - last updated and tested with pgbouncer v1.9.0
Status: pgbouncer-rr-patch merge FAILED

**Comment by rstrahan** [comment] 2019-09-10 16:47
I think this is a duplicate of #42 
For now, workaround is to checkout pgbouncer v1.10.0 and use that version for pgbouncer-rr.

Replace the documented pgbouncer clone command with:
`git clone https://github.com/pgbouncer/pgbouncer.git --branch "pgbouncer_1_10_0"`
before installing the patch.

Sorry I don't have time to fix right now - looks like the patch merge is in bouncer.h. If you can figure out how to fix please feel free to send a PR..

**Comment by chandrabh** [comment] 2020-04-24 00:31
I used pgbouncer_1_10_0 and 
got issue src/pycall.c:17:20: error: Python.h: No such file or directory

to solve that I have update below 3 file with "/usr/include/python2.6/Python.h"

src/pycall.c
rewrite_query.c
route_connection.c

and got below error:

/usr/bin/ld: cannot find -lpython2.7
collect2: ld returned 1 exit status
make: *** [pgbouncer] Error 1

Could you suggest how can I solve this

**Comment by rstrahan** [comment] 2020-04-26 20:39
@chandrabh - did you install library python-devel?  Dependencies:
libevent-devel openssl-devel python-devel libtool git patch make

**Closed** 2020-04-26 20:39 UTC

**Comment by chandrabh** [comment] 2020-04-27 04:22
Yes, I have installed all these dependencies, here below the command, I used:

sudo yum install libevent-devel openssl-devel python-devel libtool git patch make -y
