### ISSUE TITLE
Failure to build with gcc 4.8

### ISSUE THREAD

**Issue by pnorman** [awslabs/pgbouncer-rr-patch#4] opened 2015-12-29 19:03 UTC
When building with GCC 4.8, I get the error

```
gcc: error: unrecognized command line option ‘-fstack-protector-strong’
```

This seems to be because of the line

```diff
+python_CPPFLAGS = -I/usr/include/python2.7 -I/usr/include/python2.7 -fno-strict-aliasing \
+  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong \
+  --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -D_GNU_SOURCE \
+  -fPIC -fwrapv -DNDEBUG -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 \
+  -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches \
+  -m64 -mtune=generic -D_GNU_SOURCE -fPIC -fwrapv
```
(line split for readability)

hard-coding all of these options seems like a bad idea - shouldn't the build system be selecting these?

python_CPPFLAGS has some other issues

- it's not clear how `-Wall` and other options are related to python.
- ``-O2 -g`` and a large portion of the flags are duplicated

**Comment by rstrahan** [comment] 2015-12-29 23:04
Hi Paul,
I wasn't able to reproduce the compile failure on my end - I tried gcc 4.8.3 and 4.8.5 on RHEL.    
However, you are right about the unnecessary compile flags. I have checked in a new version of Makefile.diff with a simplified definition for python_CPPFLAGS.. Much tidier, and I hope it will also have the effect of resolving your issue since the problematic flag is gone. 
If you still have compile issues, please let me know, and we'll try to get to the bottom of it.
Thanks for logging the issue - very much appreciated.

**Closed** 2015-12-29 23:06 UTC
